apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-cluster-manager-chaos
  namespace: chaos-mesh

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-cluster-manager-chaos
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-cluster-manager-chaos
subjects:
- kind: ServiceAccount
  name: account-cluster-manager-chaos
  namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: role-cluster-manager-chaos
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: account-cluster-manager-chaos-token
  namespace: chaos-mesh
  annotations:
    kubernetes.io/service-account.name: account-cluster-manager-chaos
type: kubernetes.io/service-account-token
