apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attic-server
  namespace: attic
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: attic.k3s.gillouche.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: attic-server
                port:
                  number: 80
