apiVersion: v1
kind: Service
metadata:
  name: attic-server
  namespace: attic
spec:
  selector:
    app.kubernetes.io/name: attic-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
