apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-sync-succeeded.webhook.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.webhook.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.webhook.discord: ""
    notifications.argoproj.io/subscribe.on-deployed.webhook.discord: ""
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 38.0.2
    helm:
      values: |
        deployment:
          replicas: 3
        ports:
          traefik:
            port: 9999
            expose:
              default: false
          web:
            port: 9000
            expose:
              default: true
            exposedPort: 9000
            protocol: TCP
            forwardedHeaders:
              trustedIPs:
                - 192.168.0.253
          websecure:
            port: 9443
            expose:
              default: true
            exposedPort: 9443
            protocol: TCP
            forwardedHeaders:
              trustedIPs:
                - 192.168.0.253
        service:
          enabled: true
          type: LoadBalancer
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        # Set web as the default entrypoint
        additionalArguments:
          - "--entrypoints.web.address=:9000"
          - "--entrypoints.websecure.address=:9443"
          - "--entrypoints.default.entrypoints=web"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - traefik
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-class
                      operator: In
                      values: ["rpi5"]
                    - key: storage
                      operator: In
                      values: ["ssd", "sdcard"]
                    - key: reliability
                      operator: In
                      values: ["best-effort", "stable"]
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
