- Infrastructure:
    - Kubernetes Dashboard:
        icon: kubernetes
        href: https://dashboard.k3s.gillouche.homelab
        description: Cluster Management
    - ArgoCD:
        icon: argocd
        href: https://argocd.k3s.gillouche.homelab
        description: GitOps Continuous Delivery
    - Longhorn:
        icon: longhorn
        href: https://longhorn.k3s.gillouche.homelab
        description: Distributed Block Storage
    - Goldilocks:
        icon: goldilocks
        href: https://goldilocks.k3s.gillouche.homelab
        description: Resource Recommendation

- Monitoring:
    - Grafana:
        icon: grafana
        href: https://grafana.gillouche.homelab
        description: Metrics & Dashboards
    - Prometheus:
        icon: prometheus
        href: https://prometheus.gillouche.homelab
        description: Time-series Database

- Network:
    - Pi-hole:
        icon: pi-hole
        href: https://pihole.gillouche.homelab
        description: DNS Sinkhole
