apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: k8singresstls
spec:
  crd:
    spec:
      names:
        kind: K8sIngressTLS
  targets:
  - rego: "package k8singresstls\n\nviolation[{\"msg\": msg}] {\n  input.review.object.kind\
      \ == \"Ingress\"\n  not input.review.object.spec.tls\n  msg := \"Ingress resources\
      \ must define TLS\"\n}\n"
    target: admission.k8s.gatekeeper.sh
