apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
        forward . 1.1.1.1
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.0.76 rpi4b8g1
    192.168.0.77 rpi4b8g2
    192.168.0.78 rpi4b8g3
    192.168.0.79 rpi4b8g4
    192.168.0.80 rpi5b8g1
    192.168.0.81 rpi5b16g1ssd
    192.168.0.82 rpi5b16g2ssd
    192.168.0.83 rpi5b16g3ssd
    192.168.0.84 rpi5b16g4
    192.168.0.85 rpi5b16g5
    192.168.0.86 rpi5b16g6
    192.168.0.87 homeserver
    192.168.0.88 homeserver2
    192.168.0.89 homeserver3
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
