apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
        forward . 1.1.1.1
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.0.76 rpi4b8g1
    192.168.0.77 rpi4b8g2
    192.168.0.78 rpi4b8g3
    192.168.0.79 rpi4b8g4
    192.168.0.80 rpi5b8g1
    192.168.0.81 rpi5b16g1ssd
    192.168.0.82 rpi5b16g2ssd
    192.168.0.83 rpi5b16g3ssd
    192.168.0.84 rpi5b16g4
    192.168.0.85 rpi5b16g5
    192.168.0.86 rpi5b16g6
    192.168.0.87 homeserver
    192.168.0.88 homeserver2
    192.168.0.89 homeserver3
    2a02:2788:a4:5f0:e1:ff9f:e313:4a7 rpi5b16g5
    2a02:2788:a4:5f0:2ecf:67ff:fe27:2f85 rpi5b8g1
    2a02:2788:a4:5f0:2ecf:67ff:fef4:c80d rpi5b16g6
    2a02:2788:a4:5f0:2ecf:67ff:fef4:cb22 rpi5b16g4
    2a02:2788:a4:5f0:8aa2:9eff:fe57:42de rpi5b16g3ssd
    2a02:2788:a4:5f0:8aa2:9eff:fe57:430a rpi5b16g1ssd
    2a02:2788:a4:5f0:8aa2:9eff:fe57:4310 rpi5b16g2ssd
    2a02:2788:a4:5f0:da3a:ddff:fe9a:8be7 rpi4b8g4
    2a02:2788:a4:5f0:e65f:1ff:feac:1a23 rpi4b8g3
    2a02:2788:a4:5f0:e65f:1ff:feb4:a266 rpi4b8g2
    2a02:2788:a4:5f0:e65f:1ff:feb4:a280 rpi4b8g1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
