apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sIngressTLS
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: enforce-ingress-tls
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - networking.k8s.io
      kinds:
      - Ingress
    namespaceSelector:
      matchExpressions:
      - key: policy-tier
        operator: In
        values:
        - playground
