---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: secrets
spec:
  encryptedData:
    token: AgBQoK3lvW1ZeAFTM70remK4p1gapD4NqpWV0TPYA4RjaFJ25456X1iwrCaIEMIj2QE9OS/a2YhqX6RzjM4jQWLkZqh2/PvtU7dkG8Ym3lkfo6lb+Lvye1A7y5O4jjZTamxP50xi3rx9BZqzDnUKoAQNjKavvgRUCgFl+fyrFFDr6fhl6TkR1GX34ekruF1SWhNrYgF2Wb/Da2csBcZiNla9VUCKlqRboordRqvBZodmpKu2oVGRMVIZxXsekDs/IG3WsCSQ8ZhY9mhHTLoDpHzwEV0zLxIfQ8P3MXy1wK6iek8LZWnSrB+haO0MM+nlk3s57iwOeV7BMhZU1la/g1uCU4wCdy/ZHfrwSeyEfPHBpK/mTfQRlq1xC4FSD2JW+s55/zuIbVyMSrOjkcMHlG2vfA/eLyUS+PouhFFpZanBHG9m3Jq0B4vYSdNIpvtF4uCFEeG/W5ZMR0+pSKZQwG9fgX6AgyC6PwAqTZ7juwrSK7BItlkOLi5cMMp4CNdQjDzBmErMbPVG4r7bjV/ccp30tKqaQge2h/RIzkzkl/rTHQ4xW4nB0SIApviIo67xzCETVZxwwlvehVXxdl5tx3gC11wkqeuHW7oq/d62qhGJV3h83yCbJp7kCJZKs4Kj8C3WQHLg7xXpnJXEqvogUUVtxiu36dpgqyX6jBIqA+qvKLG3WeMmRHz6Z6Zjpeo9uIY2o0HWSTMWT8pyLbgfoW6vXfUnONZ7helBkROyITAHWPQrCQXtZ5GdJuibQdDTLNd2OqK7+yN9f8dktkIfncPM2LVHXQ7Po1iXaH+08NldJH/IiE6aAsGRtdsXNhw=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: renovate
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: renovate-config
      namespace: secrets
    type: Opaque
