---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: secrets
spec:
  encryptedData:
    token: AgCe8YiddvDuNlczXaqfxqlgd6/Qxz1nFPCUn6Xqxz+TFvlB/nRfdg7Xsaj+TCKvua7E/0HajwiLxN4ESAp36H114oZTGOEL1mxLnHEyXI1NI2HnH8T9gkuKFXJXgh1Igfuqs7Hm5QN6QbIlINiOPCsmAhvQ+ek+47vLdPfay5Wq8NuJ3y+SdJ1ETPt6C4+aiDoALTTgupEiRL7QII3fXURzktFn1OTnHSy30fN1CB+6mVNesCI51X6/cnGtoCzvP7SOLmOg77+pnpwxmPeNj4Z+9h1QSH6dmJ3tA2b+iRmZIIP1BZ2+/YmaO5G1M/qUR69WlZrwSTDuWxXO6BMnfxH0l+SR2y1bGCiCHMgjYL2xAYng8NoUHunPjPb7M+d3/5o4hdZ7DzyeUo2NUgjbVcuc4g2QpP97YIBVJ6rN1VpBIoe/C0zMXmdgsruJfIguV79i1c0mQiGqm6ZpRYSsOT5YaRjA0oNSWq0JCaKIsKMKmiczhxBMACgQ8i902/HpHbXsjCXCyc3gvwo1zYLBtPkI2vuykXWsim3UMqlvaS+0TVI1XEwgq3pMNdrrG3DaKcHDz3tNTPDF9a21gFMKOLrDFwULTSfEIMz7f2hh4aYRFNAcyxXsLKqLk0SzXTQZgxKtcdukwZjdflMxCdUUvQionndiOghwDGP1U5kOUxhOT8HyI6kQzTvDJ9ENiPfXYOkUYxtA1P536odH3clsdsRlHc8txPBMpJJ38vglGizgU5bKvZGmKQVB+jd4MJL0iZAxbjymL+qkT7FGAaj5/96rf5FdDA4L/slW3sgnKcn3FnbZh44IHf9VCQ4r488=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: renovate
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: renovate-config
      namespace: secrets
    type: Opaque
