---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: secrets
spec:
  encryptedData:
    token: AgCt+YzCrKRmujmFndu+nPzi4F07pjXEAu9jMNIOQnsGw0Nej+5Ws8JfSTFj7lNcIHt73qeXLqJWWxKTPvV5Lzw07D+qBULWSgohVB6zwS77V2iSTwZUt4ebF/Usqxef7l4aB9x4gQwYu7cHGwjKF1y+T1Im57JNuRhbX8jtEHHVwj1cvb6KdSPFbd143TJ6BcNvn59afDbII1mlN5HHVDbuwwNis3auyhN0vI0spUcJTIZcqYdR0Ton45xV2Tar6xIHtz7yFgsUplQgVTNcy3bi6SVTNKxavMegoXQ9XXe2JEQaq7QbkDj2MqMhPGPk6r5uIOCrF/yipFUSc0XbsheMFwpdgpJ29Fr+w+c7aJWwXURgiVOtGRmRf53jzoyVjmH3LspTVjFGp1N6+NcCpDZ3bccHzkxqeptONT7YuuVNOJGfjzObaTNre1EOv+Njq4Atk7YVMOXL+ZJNdWrDHS6W/26uMoMAxeXS7l0OmK9xl1amfhjNnENat58vqjCL/90yu8mNniK5MtH+d2lpM/fDfP9OsY2kD5FrJQYZV7rF4yff6CUQlcjrxgHJeMn9yI7IbL4VYIr+7o2Bvv5XM1m+9gccxwRwMT7DrNHvDznjfjSn78EHFHL+OAU0iT/x2kqxE7dyzEp1tH/YlHJRrCxLuViIvmNLsk2sUvjHXOfb8TA8U+IyDcxJtaADvwBbTsr1P681iux0bv5+CsiQ3Igh3E8Z6YcqxZ/EVkAuqVuSMkp8FYuMvxbX+NfUpnImouujB4hm7tLAz1Zf0P7A+5cpH5bIxwc6lPfCFYL9LCUFkwgtlBu2AkIxqsGCAsA=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: renovate
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: renovate-config
      namespace: secrets
    type: Opaque
