---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: secrets
spec:
  encryptedData:
    token: AgCNL3KjzhlX2AFkOgF1tmHlBp9Fsp6/87KuEJl3KgHH81h+9KXxGMvEyhGZlxMnRzrhvl+EpIPD1Ikvfj+GUtAtNtq2LM5+eEVwVXEyMMz2ZDu/UEsD3me6SdtEZ/0pxt+nQWug1a1ytIN0o/W9HJTz5MzHFBahE7LMWtYulkyesrrFaRDRr/04BC4zhvST8Wv4mJTab5B5mInBT0kwXRV3EPqtlEVq6R1Jc2PBnDRshw1RCxuKfgeIo8bkogyrDZqcVYjs6MtRZju2tpckjcP+npOmLfmDfyLYdUNDAMoHv1ET7wd3w7TN3ZkDf17o/00ETlvP4ZfPv1AgxbFuos3MjxgqkkBBiS+ctYn82GhGwPYjlfijj1ru/0zOEm16dYLyo6g2p8m1uZPVQDIyGv5CJxFlVEDcmzy3HoI8kFOD9oAIcGguZhNMv+DN9PVxiYRRvHEnZGc28L6+uH0TA+BTTIE2ZbtYzd62OwNX1IU0KYSVBbZEnv1UBdylZSBTPjvH1JfMTLMByIeFrQi94XKkhlFVRT0Yw2H2ZU//o7FmIj43jw3ptGTNrk31haGw+ZIEoHhEtq7oBwErYluG1NOc62iGFlVPBfFgqdaY23e06QA7Yu5j3aF5nMC77sFyxo6HAUKoQ86/atJXiP9apr5ZC9bp8OUrD2Uz8EIygNhayBdhqVDGaW1VsKNe4KKeWXapisf65UpH0laCw3V79wp2zhGLGoPokyyn7gf+1FBjECTMctZKr9p8j70oUTtMMWU9towvMuJx92GtRIKjaBEys4yJIfpWjUZmiARUQBtiFWxCNhqr9bdNkrq1leA=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: renovate
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: renovate-config
      namespace: secrets
    type: Opaque
