---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: secrets
spec:
  encryptedData:
    token: AgB5pex1yMnKVR4b/W9c93jDvQ/Odtn4tyRa3OKOLAeOfrGI0kgmEKnxryABcEfjS8QTvyblN3HDr81Drj0Wia+SiD/sbgW/wP3+59mil/K2NMTC1q5fgIfM1r898VxlkNhJ+P1zkCNd78Dmm+H/ANHcbD3/E7mhj/dn9dyE5kDm7kIq6X+UtCqOHB4UwBw/47U4712sGqKbC1eFR/zOQRsQPpK4ehUKaoyjBjFIhrjRBXkX+UzTuHgQL5b9iQ/kFG1v8AFRT2/KEhws3um0NNPhKzU8Nukwc541JPnL9ImMioKcyTsw/538/pK0/wLUiw/azrXdsSH4fWuXIRJwXirosxceS1mMNnzaUlBuN/LQ3KMoPTO2VOq18ksHKBw4WyIyqf1MLhrF3ZEkQQZs1mkrfEHXLzICVAY6e7lBkqcBu3jEO3Y7Ipf4qbCezTDgaDEHr8CBtVarcwuuhhSrf3by9Viy8sJolPOZe0Zq5CePBoyqb9s/oU0jot0e0lKYrbVVxvGtYjz3cH5XB6ZF4aCm+hElsxVZ7Zdla0QGggAWN7ccSrM2n7c/GwQ4hldBvbW7Pww4n37468lq9o+g8zQHX5iUYh8DyiJOi+WkznWMLe2HSav1IbRFWskdtNXVFBF5v7Hl0z4aYWuXf6uwxv83bW/qxPwyqELdAeMDjg5DqTioTZ9c2KsPEN6LSM8WcqTuMnGWvF/LGLe8E6bWdFNwdwjwbkn5uvl3hcGlYlgbeHJv8FU3bi92GDdkAiHLdXTvf5Y5VNB0YToiUnFf1OIEtT7jDEaJQFsW31lRksIeSp2QRZ7ba9RdY5UlIAY=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: renovate
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: renovate-config
      namespace: secrets
    type: Opaque
