apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-discord-relay
  namespace: renovate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renovate-discord-relay
  template:
    metadata:
      labels:
        app: renovate-discord-relay
    spec:
      nodeSelector:
        node-class: homeserver
      containers:
        - name: relay
          image: nexus.gillouche.homelab/docker-hosted/renovate-discord-relay:latest
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: renovate-notifications-secret
                  key: renovate-updates
---
apiVersion: v1
kind: Service
metadata:
  name: renovate-discord-relay
  namespace: renovate
spec:
  selector:
    app: renovate-discord-relay
  ports:
    - port: 3000
      targetPort: 3000
